stages:
    - test
postman_tests: 
    stage: test
    image: 
        name: postman/newman_alpine33
        entrypoint: [""]
    script:
        - newman --version
        - npm install -g newman-reporter-html
        - newman run TestedaApi_reqres.postman_collection.json --reporters cli,html --reporter-html-export teste.html
    artifacts:
        paths:
        - teste.html
        

