stages:
    - Synthetic Tests
  
  synthetic-tests:
    stage: Synthetic Tests
    image: node:latest
    script:
      - npm i
      - npm run clean
      - npm test
    artifacts:
      when: always
      expire_in: 1 week
      reports:
        junit: reports/newman-run-report-*.xml
      paths:
        - reports/
# stages:
#     - test
#     - build
# postman_tests:
#     stage: test
#     image: 
#         name: postman/newman_alpine33
#         entrypoint: [""]
#     script:
#         - newman --version
#         - npm install -g newman-reporter-html
#         - newman run API_req/TestedaApi_reqres.postman_collection.json --reporters cli,html --reporter-html-export teste.html
#     artifacts:
#         when: always
#         paths:
#             - teste.html
#     stage: build
#     script:
#         - newman --vesion
    # stage: test
    # image: 
    #     name: postman/newman_alpine33
    #     entrypoint: [""]
    # script:
    #     - newman --version
    #     - npm install -g newman-reporter-html
    #     - newman run API_req/TestedaApi_reqres.postman_collection.json --reporters cli,html --reporter-html-export teste.html
    # artifacts:
    #     when: always
    #     paths:
    #         - teste.html
    # # stage: test
    # # script:
    #     - newman run API_req/TestedaApi_reqres.postman_collection.json --reporters cli,html --reporter-html-export teste.html
    # artifacts:
    #     when: always
    #     paths:
    #     - teste.html


        
