stages:
    - build
    - test
postman_tests:
    stage: build
    script:
        - newman --vesion
    stage: test
    image: 
        name: postman/newman_alpine33
        entrypoint: [""]
    script:
        - newman --version
        - npm install -g newman-reporter-html
        - newman run collections/Test_Api_reqres.postman_collection.json --reporters cli,html --reporter-html-export teste.html
    artifacts:
        when: always
        paths:
            - teste.html
    
        
